spring:
  security:
    filter:
      order: -100
    jwt:
      key:
        "DreamFactory2024"
      expire:
        7

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dreamfactory?useUnicode=true&characterEncoding=utf8
    username: root
    password: 12345678

  mail:
    host: smtp.163.com
    username: yaphetlee2002@163.com
    password: HUITOROAHRVOBWHA
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
    virtual-host: /